### ISSUE TITLE
Another problem with the actions

### ISSUE THREAD

**Issue by pranav2481** [nwag/RobotKoopRasaConfig#2]
There is a new problem as shown in the following image.

![Screenshot from 2021-09-20 11-23-40](https://user-images.githubusercontent.com/52248711/133980990-c5663128-f6b3-461f-9403-23ca723d82f0.png)

**Comment by nwag** [comment]
Your firewall probably blocks the traffic to our public MQTT broker, you can set the address to your local MQTT broker in actions.py at line 56.
